{
  "name": "HoldToReply",
  "description": "Hold notification banner for 2 seconds to open reply box",
  "color": "#5865F2",
  "spec": "2",
  "authors": [
    {
      "name": "Blurski",
      "id": "1497358039718821981"
    }
  ],
  "version": "1.0.0",
  "js": "class HoldToReply{constructor(){this.name=\"HoldToReply\";this.version=\"1.0.0\";this.description=\"Hold notification banner for 2 seconds to open reply box\";this.author=\"Blurski\";this.patch=null}start(){console.log('[HoldToReply] Started');const NotificationModule=require('@enmity/metro').findModule(m=>m?.showNotification&&m?.dismissNotification);const ChannelStore=require('@enmity/metro').findStore('ChannelStore');let currentNotif=null;let overlayRef=null;let animFrame=null;this.patch=require('@enmity/patcher').inject(NotificationModule,'showNotification',function(args){const notif=args[0];if(!notif||!notif.channelId)return args;currentNotif={channelId:notif.channelId,messageId:notif.messageId,guildId:notif.guildId||null};this.injectOverlay(notif,ChannelStore,currentNotif);return args}.bind(this))}injectOverlay(notif,ChannelStore,currentNotif){const overlay=document.createElement('div');overlay.style.cssText='position:fixed;top:0;left:0;right:0;height:120px;z-index:999999;background:transparent;touch-action:none';const progress=document.createElement('div');progress.style.cssText='position:absolute;bottom:0;left:0;height:3px;background:#5865F2;width:0%;transition:none;border-radius:0 2px 2px 0';overlay.appendChild(progress);let startTime=0;let animFrame=null;overlay.addEventListener('touchstart',function(e){e.preventDefault();startTime=Date.now();progress.style.width='0%';const animate=function(){const elapsed=Date.now()-startTime;const pct=Math.min((elapsed/2000)*100,100);progress.style.width=pct+'%';if(pct<100){animFrame=requestAnimationFrame(animate)}else{this.openReplyBox(ChannelStore,currentNotif);if(overlay.parentNode)overlay.parentNode.removeChild(overlay)}}.bind(this);animFrame=requestAnimationFrame(animate)}.bind(this));overlay.addEventListener('touchend',function(e){e.preventDefault();if(animFrame)cancelAnimationFrame(animFrame);progress.style.width='0%'});overlay.addEventListener('touchcancel',function(e){if(animFrame)cancelAnimationFrame(animFrame);progress.style.width='0%'});document.body.appendChild(overlay)}openReplyBox(ChannelStore,currentNotif){if(!currentNotif)return;const channel=ChannelStore.getChannel(currentNotif.channelId);if(!channel)return;const navigate=require('@enmity/metro').findModule(m=>m?.navigate);navigate?.navigate(`/channels/${currentNotif.guildId||'@me'}/${currentNotif.channelId}`);setTimeout(function(){const input=document.querySelector('[class*=\"chatInput\"] textarea, [class*=\"textArea\"]');if(input){input.focus()}},300)}stop(){if(this.patch)require('@enmity/patcher').uninject(this.patch)}}module.exports=HoldToReply"
}
